In [28]:
from numpy.linalg import inv
import numpy as np

$$A = \left\{
       \begin{matrix}
       3 & 2 & -1 \\
       2 & -2 & 4 \\
       -1 & \frac{1}{2} & -1
      \end{matrix}
      \right\} \tag{1}$$

In [29]:
A = np.array([[3., 2.,-1.], [2., -2., 4], [-1, 1/2, -1]])
print(A)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]


$$A^{-1} = \left\{
       \begin{matrix}
       0 & -0.5 & -2 \\
       0.667 & 1.333 & 4.667 \\
       0.333 & 1.167 & 3.33
      \end{matrix}
      \right\} \tag{3}$$

In [30]:
A_1 = inv(a)
print(A_1)

[[ 0.         -0.5        -2.        ]
 [ 0.66666667  1.33333333  4.66666667]
 [ 0.33333333  1.16666667  3.33333333]]


$$ \overrightarrow{B} = \left\{
       \begin{matrix}
        1\\
        -2\\
        0
      \end{matrix}
      \right\} \tag{3}$$

In [34]:
B = np.array([[1.], [-2.], [0.]])
print(B)

[[ 1.]
 [-2.]
 [ 0.]]


$$A\overrightarrow{X} = \overrightarrow{B}$$
$$\overrightarrow{X} = A^{-1}\overrightarrow{B}\tag{2}$$

In [40]:
X = np.dot(A_1,B)           #理論解
print(X)

[[ 1.]
 [-2.]
 [-2.]]


In [38]:
z = np.linalg.solve(A,B)    #直接解方程式functionn
print(z)

[[ 1.]
 [-2.]
 [-2.]]
